using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TerrariaServerModded.Roslyn;

[Generator]
public class ChatCommandProcessor : IIncrementalGenerator
{
    private const string AttributeNamespace = "TerrariaServerModded.Chat";
    private const string AttributeName = "ChatCommandProcessorAttribute";
    private const string FullAttributeName = $"{AttributeNamespace}.{AttributeName}";
    private const string InterfaceName = "TerrariaServerModded.Chat.IChatCommand";

    private const string AttributeSource = $$"""
                                             // <auto-generated />
                                             using System;

                                             namespace {{AttributeNamespace}}
                                             {
                                                 [AttributeUsage(AttributeTargets.Class)]
                                                 public sealed class {{AttributeName}} : Attribute { }
                                             }
                                             """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(i => i.AddSource(
            $"{AttributeName}.g.cs",
            SourceText.From(AttributeSource, Encoding.UTF8)));

        var commandTypes = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: TransformChatCommands)
            .Where(static m => m is not null)
            .Collect();

        var managerClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
                FullAttributeName,
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol)
            .Collect();

        var combined = commandTypes.Combine(managerClasses);

        context.RegisterSourceOutput(combined, static (spc, source) =>
            Execute(spc, source.Left!, source.Right!));
    }

    private static string? TransformChatCommands(GeneratorSyntaxContext ctx, CancellationToken _)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) is not INamedTypeSymbol symbol)
            return null;

        var chatCommand = ctx.SemanticModel.Compilation.GetTypeByMetadataName(InterfaceName);
        if (chatCommand is null)
            return null;

        foreach (var i in symbol.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(i, chatCommand))
                return symbol.ToDisplayString();
        }

        return null;
    }

    private static void Execute(
        SourceProductionContext context,
        ImmutableArray<string> commandTypes,
        ImmutableArray<INamedTypeSymbol> processors)
    {
        if (commandTypes.IsEmpty || processors.IsEmpty)
            return;

        var sb = new StringBuilder();
        foreach (var manager in processors)
        {
            sb.Clear();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using Terraria;");
            sb.AppendLine("using Terraria.Localization;");
            sb.AppendLine("using TerrariaServerModded.Chat;");
            sb.AppendLine();
            sb.AppendLine($"namespace {manager.ContainingNamespace.ToDisplayString()};");
            sb.AppendLine();
            sb.AppendLine($"partial class {manager.Name}");
            sb.AppendLine("{");

            // Init Method
            sb.AppendLine("    public static partial void Init()");
            sb.AppendLine("    {");
            foreach (var cmd in commandTypes)
                sb.AppendLine(
                    $"        LanguageManager.Instance._localizedTexts.Add({cmd}.DescriptionKey, new LocalizedText({cmd}.DescriptionKey, {cmd}.Description));");
            sb.AppendLine("    }");
            sb.AppendLine();

            // ExecuteIfMatches Method
            sb.AppendLine(
                "    public static partial bool ExecuteIfMatches(Player player, AdditionalPlayerData? data, ReadOnlySpan<char> input)");
            sb.AppendLine("    {");
            foreach (var cmd in commandTypes)
            {
                sb.AppendLine($"        if ({cmd}.Matches(input))");
                sb.AppendLine("        {");
                sb.AppendLine($"            {cmd}.Execute(player, data, input);");
                sb.AppendLine("            return true;");
                sb.AppendLine("        }");
            }

            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // ListToClient Method
            sb.AppendLine("    public static partial void ListToClient(int playerIndex)");
            sb.AppendLine("    {");
            sb.AppendLine("        var sb = new StringBuilder();");
            foreach (var cmd in commandTypes)
                sb.AppendLine($"        sb.AppendLine({cmd}.Description);");
            sb.AppendLine(
                "        Terraria.Chat.ChatHelper.SendChatMessageToClient(NetworkText.FromLiteral(sb.ToString()), Terraria.Chat.Commands.HelpCommand.RESPONSE_COLOR, playerIndex);");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            context.AddSource($"{manager.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}