using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TerrariaServerModded.Roslyn;

[Generator]
public class CliCommandProcessor : IIncrementalGenerator
{
    private const string AttributeNamespace = "TerrariaServerModded.Cli";
    private const string AttributeName = "CliCommandProcessorAttribute";
    private const string FullAttributeName = $"{AttributeNamespace}.{AttributeName}";
    private const string InterfaceName = "TerrariaServerModded.Cli.ICliCommand";

    private const string AttributeSource = $$"""
                                             // <auto-generated />
                                             using System;

                                             namespace {{AttributeNamespace}}
                                             {
                                                 [AttributeUsage(AttributeTargets.Class)]
                                                 public sealed class {{AttributeName}} : Attribute { }
                                             }
                                             """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(i => i.AddSource(
            $"{AttributeName}.g.cs",
            SourceText.From(AttributeSource, Encoding.UTF8)));

        var commandTypes = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: TransformCliCommands)
            .Where(static m => m is not null)
            .Collect();

        var processorClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
                FullAttributeName,
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol)
            .Collect();

        var combined = commandTypes.Combine(processorClasses);

        context.RegisterSourceOutput(combined, static (spc, source) =>
            Execute(spc, source.Left!, source.Right!));
    }

    private static string? TransformCliCommands(GeneratorSyntaxContext ctx, CancellationToken _)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) is not INamedTypeSymbol symbol)
            return null;

        var cliCommand = ctx.SemanticModel.Compilation.GetTypeByMetadataName(InterfaceName);
        if (cliCommand is null)
            return null;

        foreach (var i in symbol.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(i, cliCommand))
                return symbol.ToDisplayString();
        }

        return null;
    }

    private static void Execute(
        SourceProductionContext context,
        ImmutableArray<string> commandTypes,
        ImmutableArray<INamedTypeSymbol> processors)
    {
        if (commandTypes.IsEmpty || processors.IsEmpty)
            return;

        var sb = new StringBuilder();
        foreach (var processor in processors)
        {
            sb.Clear();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using Terraria;");
            sb.AppendLine("using TerrariaServerModded.Cli;");
            sb.AppendLine();
            sb.AppendLine($"namespace {processor.ContainingNamespace.ToDisplayString()};");
            sb.AppendLine();
            sb.AppendLine($"partial class {processor.Name}");
            sb.AppendLine("{");

            // LongestCmdNameLength Property
            sb.AppendLine("    public static int LongestCmdNameLength");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            var max = 0;");
            foreach (var cmd in commandTypes)
            {
                if (cmd != "TerrariaServerModded.Cli.Commands.HelpCliCommand")
                    sb.AppendLine($"            if ({cmd}.Display.Length > max) max = {cmd}.Display.Length;");
            }
            sb.AppendLine("            return max;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // TryHandle Method
            sb.AppendLine("    public static bool TryHandle(ReadOnlySpan<char> input, out ReadOnlyMemory<byte> response)");
            sb.AppendLine("    {");
            foreach (var cmd in commandTypes)
            {
                sb.AppendLine($"        if (input.StartsWith({cmd}.Command, StringComparison.OrdinalIgnoreCase))");
                sb.AppendLine($"            return {cmd}.TryExecute(input, out response);");
            }
            sb.AppendLine("        response = default;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // List Method
            sb.AppendLine("    public static string List()");
            sb.AppendLine("    {");
            sb.AppendLine("        var sb = new StringBuilder();");
            foreach (var cmd in commandTypes)
            {
                if (cmd != "TerrariaServerModded.Cli.Commands.HelpCliCommand")
                    sb.AppendLine($$"""        sb.AppendLine($"{{{cmd}}.Display.PadRight(LongestCmdNameLength)} {{{cmd}}.Description}");""");
            }
            sb.AppendLine("        if (sb.Length > 0) sb.Length -= Environment.NewLine.Length;");
            sb.AppendLine("        return sb.ToString();");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            context.AddSource($"{processor.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}